name: flutter_ffmpeg_example
description: Demonstrates how to use the flutter_ffmpeg plugin.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  path: ^1.6.4
  path_provider: ^1.4.0
  flutter_ffmpeg: 0.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
